type Place {
  _id: ID!
  owner: User
  desciption: String
  mainPhoto: String
  photos: [String]
  priceByNight: Float
  reviews: [Review]
}

input InputPlaceType {
  type: String!
  owner: ID!
  desciption: String!
  mainPhoto: String!
  photos: [String]!
  priceByNight: Float!
}

type Mutation {
  createPlace(body: InputPlaceType!): Place
  updatePlace(_id: ID!, body: InputPlaceType!): Place
  deletePlace(_id: ID!): Place
}

type PaginationType {
  page: Int
  pages: Int
  count: Int
}

type PlaceEdgesType {
  edges: [Place]
  pagination: PaginationType
}

type Query {
  readPlace(_id: ID!): Place
  listPlace(page: Int, limit: Int, sortBy: String, sortOrder: String): PlaceEdgesType
  searchPlace(limit: Int, query: String!, fields: String!): [Place]
}
