type Place {
  _id: ID!
  owner: User
  desciption: String
  mainPhoto: String
  photos: [String]
  priceByNight: Float
  reviews: [Review]
}

input inputPlaceType {
  type: String
  desciption: String
  mainPhoto: String
  photos: [String]
  priceByNight: Float
}

type Mutation {
  placeCreate(body: inputPlaceType): Place
  placeUpdate(body: inputPlaceType): Place
  placeDelete(_id: ID): Place
}

type paginationInfo {
  page: Int
  pages: Int
  count: Int
}

type PlacePagination {
  edges: [Place]
  pagination: paginationInfo
}
type Query {
  placeList(page: Int): PlacePagination
  place(_id: ID): Place
}
