type User {
  id: ID!
  name: String
  email: String!
  photo: String!
}

input inputUserType {
  name: String!
  email: String!
}

type Query {
  userList: [User!]!
  user(id: ID!): User!
}

type Mutation {
  addUser(body: inputUserType): User!
}
