type User {
  _id: ID!
  name: String
  email: String
  photo: String
}

input inputUserType {
  name: String
  email: String
}

type PaginationType {
  page: Int
  pages: Int
  count: Int
}

type UserEdgesType {
  edges: [User]
  pagination: PaginationType
}

type Query {
  userList: UserEdgesType
  user(_id: ID): User
}

type Mutation {
  addUser(body: inputUserType): User
}
